# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/justin/dev/100k2015/cppbot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/justin/dev/100k2015/cppbot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/justin/dev/100k2015/cppbot/CMakeFiles /home/justin/dev/100k2015/cppbot/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/justin/dev/100k2015/cppbot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cppbot

# Build rule for target.
cppbot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cppbot
.PHONY : cppbot

# fast build rule for target.
cppbot/fast:
	$(MAKE) -f CMakeFiles/cppbot.dir/build.make CMakeFiles/cppbot.dir/build
.PHONY : cppbot/fast

src/alien.o: src/alien.cpp.o
.PHONY : src/alien.o

# target to build an object file
src/alien.cpp.o:
	$(MAKE) -f CMakeFiles/cppbot.dir/build.make CMakeFiles/cppbot.dir/src/alien.cpp.o
.PHONY : src/alien.cpp.o

src/alien.i: src/alien.cpp.i
.PHONY : src/alien.i

# target to preprocess a source file
src/alien.cpp.i:
	$(MAKE) -f CMakeFiles/cppbot.dir/build.make CMakeFiles/cppbot.dir/src/alien.cpp.i
.PHONY : src/alien.cpp.i

src/alien.s: src/alien.cpp.s
.PHONY : src/alien.s

# target to generate assembly for a file
src/alien.cpp.s:
	$(MAKE) -f CMakeFiles/cppbot.dir/build.make CMakeFiles/cppbot.dir/src/alien.cpp.s
.PHONY : src/alien.cpp.s

src/enemy_bullet.o: src/enemy_bullet.cpp.o
.PHONY : src/enemy_bullet.o

# target to build an object file
src/enemy_bullet.cpp.o:
	$(MAKE) -f CMakeFiles/cppbot.dir/build.make CMakeFiles/cppbot.dir/src/enemy_bullet.cpp.o
.PHONY : src/enemy_bullet.cpp.o

src/enemy_bullet.i: src/enemy_bullet.cpp.i
.PHONY : src/enemy_bullet.i

# target to preprocess a source file
src/enemy_bullet.cpp.i:
	$(MAKE) -f CMakeFiles/cppbot.dir/build.make CMakeFiles/cppbot.dir/src/enemy_bullet.cpp.i
.PHONY : src/enemy_bullet.cpp.i

src/enemy_bullet.s: src/enemy_bullet.cpp.s
.PHONY : src/enemy_bullet.s

# target to generate assembly for a file
src/enemy_bullet.cpp.s:
	$(MAKE) -f CMakeFiles/cppbot.dir/build.make CMakeFiles/cppbot.dir/src/enemy_bullet.cpp.s
.PHONY : src/enemy_bullet.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/cppbot.dir/build.make CMakeFiles/cppbot.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/cppbot.dir/build.make CMakeFiles/cppbot.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/cppbot.dir/build.make CMakeFiles/cppbot.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/player_missile.o: src/player_missile.cpp.o
.PHONY : src/player_missile.o

# target to build an object file
src/player_missile.cpp.o:
	$(MAKE) -f CMakeFiles/cppbot.dir/build.make CMakeFiles/cppbot.dir/src/player_missile.cpp.o
.PHONY : src/player_missile.cpp.o

src/player_missile.i: src/player_missile.cpp.i
.PHONY : src/player_missile.i

# target to preprocess a source file
src/player_missile.cpp.i:
	$(MAKE) -f CMakeFiles/cppbot.dir/build.make CMakeFiles/cppbot.dir/src/player_missile.cpp.i
.PHONY : src/player_missile.cpp.i

src/player_missile.s: src/player_missile.cpp.s
.PHONY : src/player_missile.s

# target to generate assembly for a file
src/player_missile.cpp.s:
	$(MAKE) -f CMakeFiles/cppbot.dir/build.make CMakeFiles/cppbot.dir/src/player_missile.cpp.s
.PHONY : src/player_missile.cpp.s

src/shield.o: src/shield.cpp.o
.PHONY : src/shield.o

# target to build an object file
src/shield.cpp.o:
	$(MAKE) -f CMakeFiles/cppbot.dir/build.make CMakeFiles/cppbot.dir/src/shield.cpp.o
.PHONY : src/shield.cpp.o

src/shield.i: src/shield.cpp.i
.PHONY : src/shield.i

# target to preprocess a source file
src/shield.cpp.i:
	$(MAKE) -f CMakeFiles/cppbot.dir/build.make CMakeFiles/cppbot.dir/src/shield.cpp.i
.PHONY : src/shield.cpp.i

src/shield.s: src/shield.cpp.s
.PHONY : src/shield.s

# target to generate assembly for a file
src/shield.cpp.s:
	$(MAKE) -f CMakeFiles/cppbot.dir/build.make CMakeFiles/cppbot.dir/src/shield.cpp.s
.PHONY : src/shield.cpp.s

src/spacebot.o: src/spacebot.cpp.o
.PHONY : src/spacebot.o

# target to build an object file
src/spacebot.cpp.o:
	$(MAKE) -f CMakeFiles/cppbot.dir/build.make CMakeFiles/cppbot.dir/src/spacebot.cpp.o
.PHONY : src/spacebot.cpp.o

src/spacebot.i: src/spacebot.cpp.i
.PHONY : src/spacebot.i

# target to preprocess a source file
src/spacebot.cpp.i:
	$(MAKE) -f CMakeFiles/cppbot.dir/build.make CMakeFiles/cppbot.dir/src/spacebot.cpp.i
.PHONY : src/spacebot.cpp.i

src/spacebot.s: src/spacebot.cpp.s
.PHONY : src/spacebot.s

# target to generate assembly for a file
src/spacebot.cpp.s:
	$(MAKE) -f CMakeFiles/cppbot.dir/build.make CMakeFiles/cppbot.dir/src/spacebot.cpp.s
.PHONY : src/spacebot.cpp.s

src/spaceship.o: src/spaceship.cpp.o
.PHONY : src/spaceship.o

# target to build an object file
src/spaceship.cpp.o:
	$(MAKE) -f CMakeFiles/cppbot.dir/build.make CMakeFiles/cppbot.dir/src/spaceship.cpp.o
.PHONY : src/spaceship.cpp.o

src/spaceship.i: src/spaceship.cpp.i
.PHONY : src/spaceship.i

# target to preprocess a source file
src/spaceship.cpp.i:
	$(MAKE) -f CMakeFiles/cppbot.dir/build.make CMakeFiles/cppbot.dir/src/spaceship.cpp.i
.PHONY : src/spaceship.cpp.i

src/spaceship.s: src/spaceship.cpp.s
.PHONY : src/spaceship.s

# target to generate assembly for a file
src/spaceship.cpp.s:
	$(MAKE) -f CMakeFiles/cppbot.dir/build.make CMakeFiles/cppbot.dir/src/spaceship.cpp.s
.PHONY : src/spaceship.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cppbot"
	@echo "... src/alien.o"
	@echo "... src/alien.i"
	@echo "... src/alien.s"
	@echo "... src/enemy_bullet.o"
	@echo "... src/enemy_bullet.i"
	@echo "... src/enemy_bullet.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/player_missile.o"
	@echo "... src/player_missile.i"
	@echo "... src/player_missile.s"
	@echo "... src/shield.o"
	@echo "... src/shield.i"
	@echo "... src/shield.s"
	@echo "... src/spacebot.o"
	@echo "... src/spacebot.i"
	@echo "... src/spacebot.s"
	@echo "... src/spaceship.o"
	@echo "... src/spaceship.i"
	@echo "... src/spaceship.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

